= Chapter Five: Controlling Bitcoin Transactions

Sending a transaction isn't always the end of the story.
Using the RBF (replace-by-fee) and CPFP (child-pays-for-parent) protocols, a developer can continue to control the transaction after it's been sent, to improve efficiency or to recover transactions that get stuck.
These methods will begin to spotlight the true power of Bitcoin.

== Objectives for This Section

After working through this chapter, a developer will be able to:

* Decide Whether RBF or CPFP Might Help a Transaction
* Create Replacement Transaction Using RBF
* Create New Transactions Using CPFP

Supporting objectives include the ability to:

* Understand the Mempool
* Understand the Difference Between RBF and CPFP
* Plan for the Power of RBF

== Table of Contents

* xref:05_1_Watching_for_Stuck_Transactions.adoc[Section One: Watching for Stuck Transactions]
* xref:05_2_Resending_a_Transaction_with_RBF.adoc[Section Two: Resending a Transaction with RBF]
* xref:05_3_Funding_a_Transaction_with_CPFP.adoc[Section Three: Funding a Transaction with CPFP]
