= Contributing

We love your input!
We want to make contributing to this project as easy and transparent as possible, whether it's:

* Reporting a bug
* Discussing the current state of the code
* Submitting a fix
* Proposing new features
* Becoming a maintainer

== We Develop with Github

We use GitHub to host code, to track issues and feature requests, and to accept Pull Requests.

== Report Bugs using Github's https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues[issues]

If you find bugs, mistakes, or inconsistencies in this project's code or documents, please let us know by https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues/new[opening a new issue], but consider searching through existing issues first to check and see if the problem has already been reported.
If it has, it never hurts to add a quick "+1" or "I have this problem too".
This helps prioritize the most common problems and requests.

=== Write Bug Reports with Detail, Background, and Sample Code

http://stackoverflow.com/q/12488905/180626[This is an example] of a good bug report by @briandk.
Here's http://www.openradar.me/11905408[another example from craig.hockenberry].

*Great Bug Reports* tend to have:

* A quick summary and/or background
* Steps to reproduce
 ** Be specific!
 ** Give sample code if you can.
http://stackoverflow.com/q/12488905/180626[The stackoverflow bug report] includes sample code that _anyone_ with a base R setup can run to reproduce what I was seeing
* What you expected would happen
* What actually happens
* Notes (possibly including why you think this might be happening, or stuff you tried that didn't work)

People _love_ thorough bug reports.
I'm not even kidding.

== Submit Code Changes through Pull Requests

Simple Pull Requests to fix typos, to document, or to fix small bugs are always welcome.

We ask that more significant improvements to the project be first proposed before anybody starts to code as an https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/issues[issue] or as a https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/pulls[draft Pull Request], which is a https://github.blog/2019-02-14-introducing-draft-pull-requests/[nice new feature] that gives other contributors a chance to point you in the right direction, give feedback on the design, and maybe discuss if related work is already under way.

=== Use a Consistent Coding Style

* We indent using two spaces (soft tabs)
* We ALWAYS put spaces after list items and method parameters ([1, 2, 3], not [1,2,3]), around operators (x += 1, not x+=1), and around hash arrows.
* This is open-source software.
Consider the people who will read your code, and make it look nice for them.
It's sort of like driving a car: Perhaps you love doing donuts when you're alone, but with passengers the goal is to make the ride as smooth as possible.

=== Use https://guides.github.com/introduction/flow/index.html[Github Flow] for Pull Requests

We use https://guides.github.com/introduction/flow/index.html[Github Flow].
When you submit Pull Requests, please:

. Fork the repo and create your branch from `master`.
. If you've added code that should be tested, add tests.
. If you've changed APIs, update the documentation.
. Ensure the test suite passes.
. Make sure your code lints.
. Issue that Pull Request!

=== Submit Under the BSD-2-Clause Plus Patent License

In short, when you submit code changes, your submissions are understood to be available under the same xref:./LICENSE-CC-BY-4.0.adoc[CC-BY] license that covers the project.
We also ask all code contributors to GPG sign the xref:./CLA.adoc[Contributor License Agreement (CLA.md)] to protect future users of this project.
Feel free to contact the maintainers if that's a concern.

== References

Portions of this CONTRIBUTING.md document were adopted from best practices of a number of open source projects, including:

* https://github.com/facebook/draft-js/blob/master/CONTRIBUTING.md[Facebook's Draft]
* https://github.com/ipfs/community/blob/master/CONTRIBUTING.md[IPFS Contributing]
